Update fortify-scan.yml

diff --git a/.github/workflows/fortify-scan.yml b/.github/workflows/fortify-scan.yml
--- a/.github/workflows/fortify-scan.yml
+++ b/.github/workflows/fortify-scan.yml
@@ -23,6 +23,8 @@ jobs:
     env:     
       APPLICATION: "${{ github.event.repository.name }} GitHub"
       VERSION: "${{ github.ref_name }}"
+      APPLICATION_FROM: "${{ github.event.repository.name }} GitHub"
+      VERSION_FROM: "main"
     
       FTFY_SSC_URL: ${{ vars.FTFY_SSC_URL }}
       FTFY_SC_CONTROLLER_URL: ${{ vars.FTFY_SC_CONTROLLER_URL }}
@@ -85,7 +87,77 @@ jobs:
       # Create AppVersion
       - name: Create Application Version
         run: |
-          fcli ssc appversion create "${APPLICATION}":"${VERSION}" --auto-required-attrs --skip-if-exists
+          appVersionSearch=$(fcli ssc appversion ls -q=application.name="$APPLICATION" -q=name="${VERSION}")
+
+          if [[ $appVersionSearch = "No data" ]]; then
+            echo "Application Version $APPLICATION:$VERSION not found. Creation init";
+          
+            echo "Retrieving Application ID"
+            projectId=$(fcli ssc app get "${APPLICATION}" -o expr={id})
+            echo "ApplicationId = $projectId"
+          
+            echo "Creating Application Version"
+            body="{
+                \"name\": \"$VERSION\",
+                \"description\": \"\",
+                \"active\": true,
+                \"committed\": false,
+                \"project\": {
+                    \"id\": $projectId
+                }
+            }"
+          
+            applicationVersionId=$(fcli ssc rest call /api/v1/projectVersions -d "$body" -X POST -o expr={data.id})
+            echo "Application Version created with id $applicationVersionId"
+          
+            echo "Copy Application State from \"$APPLICATION\":$VERSION to \"$APPLICATION_FROM\":$VERSION_FROM "
+            echo "Searching for \"$APPLICATION_FROM\":$VERSION_FROM"
+          
+            appVersionSearch=$(fcli ssc appversion ls -q=application.name="${APPLICATION_FROM}" -q=name="${VERSION_FROM}")
+            if [[ $appVersionSearch = "No data" ]]; then
+                  echo "Application Version $APPLICATION_FROM:$VERSION_FROM not found. Skipping Copy State";
+            else
+              echo "Application Version $APPLICATION_FROM:$VERSION_FROM found"
+              fromApplicationVersionId=$(fcli ssc appversion get "$APPLICATION_FROM":$VERSION_FROM -o expr={id})
+              echo "Application Version $APPLICATION_FROM:$VERSION_FROM id: $fromApplicationVersionId"
+          
+              echo "Copy State init"
+              body="{
+                      \"copyAnalysisProcessingRules\": \"true\",
+                      \"copyBugTrackerConfiguration\": \"true\",
+                      \"copyCustomTags\": \"true\",
+                      \"previousProjectVersionId\": \"$fromApplicationVersionId\",
+                      \"projectVersionId\": \"$applicationVersionId\"
+                    }"
+              status=$(fcli ssc rest call /api/v1/projectVersions/action/copyFromPartial -d "$body" -X POST -o expr={responseCode})
+          
+              if [[ $status = 200 ]] ; then
+                echo "Copy State SUCCESS. Commiting Application Version"
+                body='{"committed": "true"}'
+                status=$(fcli ssc rest call /api/v1/projectVersions/$applicationVersionId -d "$body" -X PUT -o expr={responseCode})
+                if [[ $status = 200 ]] ; then
+                        echo "Application Version commited."
+                else
+                  echo $status
+                  echo "Something went wrong while commiting Application Version"
+                fi
+              fi
+              if [[ $status != 200 ]]; then
+                echo $status
+                echo "Copy State FAILURE. Deleting Application"
+                status=$(fcli ssc rest call /api/v1/projectVersions/$applicationVersionId -X DELETE -o expr={responseCode})
+                if [[ $status = 200 ]] ; then
+                  echo "Application Version deleted."
+                else
+                  echo $status
+                  echo "Something went wrong while deleting Application Version"
+                fi
+                exit 1
+              fi
+            fi
+          else
+            echo "Application Version \"$APPLICATION\":$VERSION already exists. Skipping";
+          fi
 
       ## SAST
       # Package sources
